Order by ad  and proposal testcases
haite4/cypress_team pull request #5
Opened 2024-11-22 05:22 UTC by haite4

2024-11-22 07:25 UTC, gantz26 commented on cypress/constants/colors.ts
> +    StrongRed = "rgb(247, 56, 89)"
Краще використовувати один стиль для написання констант, наприклад, UPPER_SNAKE_CASE

2024-11-22 07:25 UTC, gantz26 commented on cypress/e2e/editUnit.cy.ts
>        cy.wait(2000);
Я розумію, що інколи без wait ніяк, але, якщо можливо, то краще замінити їх на методи очікування необхідного елементу

2024-11-22 07:25 UTC, gantz26 commented on cypress/pages/page.ts
> +}
У loginPage.ts є такий метод, announcementsButton. Використовуй його або видали та заміни всі його виклики у коді на свій метод. І з строки '[class*="Navbar_link__UhyJF"]' краще прибрати останню частину з рандомними літерами

2024-12-02 09:24 UTC, IlyaKosts commented on cypress/helper/dateTime.ts
> +      getSpecificDate(){
@haite4 До таких великих медодів краще додати TSDoc з коротким описом, так буде одразу видно й зрозуміло навіщо він й що повертає. Це спростить обслуговування й його використання у майбутньому.

2024-12-02 09:36 UTC, IlyaKosts commented on cypress/pages/unitsPage.ts
> +    return cy.get("button").contains("Деактивувати");
@haite4 У таких випадках ви можете просто використовувати 'contains' метод: cy.contains('button', 'Деактивувати'). Надійніше у кейсі з кнопками + таким чином можете брати елемент вищий у дереві ніж той що містить вказаний текст. (Це просто справка, код все гуд).

2024-12-02 09:42 UTC, IlyaKosts commented on package.json
> +    "cy:proposal": "npx cypress run --spec cypress/e2e/proposal.cy.ts --browser chrome",
@haite4 Ці команди необхідні, їх потребують? Просто всього тест кейсів близбко 400, цих комманд потям буде мільярд. Якщо ви бажаєте реалізувати зручний запуск з консолі конкретного тест спеку - створіть баш файл, в якого буде опція на ім'я тест спеку, так не буде потреби кожен раз створювати команду + зручніше для іншух хто буде їх запускати.

2024-12-02 09:49 UTC, IlyaKosts commented on package.json
>      "cy:favouriteUnits:headless": "npx cypress run --spec cypress/e2e/favouriteUnits.cy.ts --browser chrome --headed",
@haite4 У хедлесс комманди стоїть ' --headed' опція. Взагалі навіщо headed команди тут потрібні? cypress open й є хед режим для сайпресса, із зручним UI який просто убирає майже весь сенс у таких командах для цього фреймворку (як мінімум в таких випадках).

2024-12-09 10:59 UTC, IlyaKosts commented on cypress/e2e/editUnit.cy.ts
>        cy.wait(2000);
@haite4 Btw, часто на такі випадки можна використати інтерцептор - https://docs.cypress.io/api/commands/intercept, та потім чекати на апіху.

2024-12-09 11:01 UTC, IlyaKosts requested changes
@haite4 Додав коммент за баш файл та команди.

2024-12-09 17:10 UTC, haite4 commented on cypress/e2e/editUnit.cy.ts
>        cy.wait(2000);
@IlyaKosts  intercept  в данному випадку  не можливо використовувати, так як запит не був ініціалізованний щоб його  перехопити.

2024-12-13 13:45 UTC, IlyaKosts commented
@haite4 Все гуд! Тільки не забудьте оновити README, у іншому - good to go.

2024-12-16 17:26 UTC, IlyaKosts approved these changes
Good to go!

2024-12-17 11:58 UTC, merged